# 20 뉴스그룹 분류

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import fetch_20newsgroups
news_data = fetch_20newsgroups(subset='all', random_state=156)

### 데이터 탐색

In [3]:
news_data.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [4]:
print('target 클래스의 값과 분포도')
print(pd.Series(news_data.target).value_counts().sort_index())

target 클래스의 값과 분포도
0     799
1     973
2     985
3     982
4     963
5     988
6     975
7     990
8     996
9     994
10    999
11    991
12    984
13    990
14    987
15    997
16    910
17    940
18    775
19    628
dtype: int64


In [5]:
print('target 클래스의 이름들 \n', news_data.target_names)

target 클래스의 이름들 
 ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [6]:
print(news_data.data[0])

From: egreen@east.sun.com (Ed Green - Pixel Cruncher)
Subject: Re: Observation re: helmets
Organization: Sun Microsystems, RTP, NC
Lines: 21
Distribution: world
Reply-To: egreen@east.sun.com
NNTP-Posting-Host: laser.east.sun.com

In article 211353@mavenry.altcit.eskimo.com, maven@mavenry.altcit.eskimo.com (Norman Hamer) writes:
> 
> The question for the day is re: passenger helmets, if you don't know for 
>certain who's gonna ride with you (like say you meet them at a .... church 
>meeting, yeah, that's the ticket)... What are some guidelines? Should I just 
>pick up another shoei in my size to have a backup helmet (XL), or should I 
>maybe get an inexpensive one of a smaller size to accomodate my likely 
>passenger? 

If your primary concern is protecting the passenger in the event of a
crash, have him or her fitted for a helmet that is their size.  If your
primary concern is complying with stupid helmet laws, carry a real big
spare (you can put a big or small head in a big helmet, bu

### 훈련/테스트용 데이터 추출

In [7]:
train_news = fetch_20newsgroups(subset='train', random_state=156, remove=('headers', 'footers', 'quotes'))
X_train = train_news.data
y_train = train_news.target

In [8]:
print(train_news.data[0])



What I did NOT get with my drive (CD300i) is the System Install CD you
listed as #1.  Any ideas about how I can get one?  I bought my IIvx 8/120
from Direct Express in Chicago (no complaints at all -- good price & good
service).

BTW, I've heard that the System Install CD can be used to boot the mac;
however, my drive will NOT accept a CD caddy is the machine is off.  How can
you boot with it then?

--Dave



In [9]:
train_news.target[0] # 4는 comp.sys.mac.hardware

4

In [10]:
test_news = fetch_20newsgroups(subset='test', random_state=156, remove=('headers', 'footers', 'quotes'))
X_test = test_news.data
y_test = test_news.target

In [11]:
len(X_train), len(X_test) #데이터가많드아~

(11314, 7532)

### 피처 벡터화 변환과 머신러닝 모델 학습/예측/평가
- Case 1. CountVectorizer

In [12]:
# 트레인데이터를 숫자로 바꾸기 CountVectorizer 또는 TfidfVectorizer 사용해서
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer() 
count_vect.fit(X_train)
X_train_count = count_vect.transform(X_train) # 꼭 두단계를 거쳐야 train, test같은 인덱스를 가짐
X_test_count = count_vect.transform(X_test)

In [13]:
X_train_count.shape #뉴스11314개, 뉴스안의 단어수 101631개

(11314, 101631)

In [14]:
#분류
#숫자는 로지스틱리그레션(성능이좋음), svc 써도 됨
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()
lr_clf.fit(X_train_count, y_train) # 문서 X_train를 주면 안됨

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
from sklearn.metrics import accuracy_score

pred = lr_clf.predict(X_test_count)
accuracy_score(y_test, pred) #정확도 60.7%

0.6074083908656399

In [16]:
print(y_test[:5])
print(pred[:5]) # 조금 빗나가 예측했지만 ㅋㅋ 그래도 얼추;1개틀리고, 다맞춤

[ 4 11  1  7  8]
[ 4 11  6  7  8]


- Case 2. TfidVectorizer

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(X_train)
X_train_tfidf = tfidf_vect.transform(X_train) # 꼭 두단계를 거쳐야 train, test같은 인덱스를 가짐
X_test_tfidf = tfidf_vect.transform(X_test)

In [18]:
X_train_tfidf.shape #모양은 같은, 가중치부여한 실수가 나오는 것일 뿐.

(11314, 101631)

In [19]:
#분류
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()
lr_clf.fit(X_train_tfidf, y_train) 
pred = lr_clf.predict(X_test_tfidf)
accuracy_score(y_test, pred) #67.3% 정확도는 더 높음

0.6736590546999469

In [20]:
print(y_test[:5])
print(pred[:5]) #2개틀림;;  ____ 상황에따라 각각 다르다

[ 4 11  1  7  8]
[5 1 1 7 8]


#### 학습에 사용된 파라미터

In [21]:
print(tfidf_vect.get_params())

{'analyzer': 'word', 'binary': False, 'decode_error': 'strict', 'dtype': <class 'numpy.float64'>, 'encoding': 'utf-8', 'input': 'content', 'lowercase': True, 'max_df': 1.0, 'max_features': None, 'min_df': 1, 'ngram_range': (1, 1), 'norm': 'l2', 'preprocessor': None, 'smooth_idf': True, 'stop_words': None, 'strip_accents': None, 'sublinear_tf': False, 'token_pattern': '(?u)\\b\\w\\w+\\b', 'tokenizer': None, 'use_idf': True, 'vocabulary': None}


In [22]:
print(lr_clf.get_params())

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


- Case 3. stop_words filtering, ngram(1,2), max_df = 300 으로 변경해서 

In [23]:
#그리드서치cv사용하면 50분도 더 걸릴 수있음;;
tfidf_vect = TfidfVectorizer(stop_words='english', ngram_range=(1,2), max_df=300)
tfidf_vect.fit(X_train)
X_train_tfidf = tfidf_vect.transform(X_train) # 꼭 두단계를 거쳐야 train, test같은 인덱스를 가짐
X_test_tfidf = tfidf_vect.transform(X_test)

In [24]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()
lr_clf.fit(X_train_tfidf, y_train) 
pred = lr_clf.predict(X_test_tfidf)
accuracy_score(y_test, pred) #69% 쪼끔 올라감.

0.6922464152947424

In [25]:
print(y_test[:5])
print(pred[:5]) #1개틀림

[ 4 11  1  7  8]
[ 3 11  1  7  8]


 - Case 4. Case3에서 LogisticRegression C값을 10으로

In [27]:
lr_clf = LogisticRegression(C=10)
lr_clf.fit(X_train_tfidf, y_train) 
pred = lr_clf.predict(X_test_tfidf)
accuracy_score(y_test, pred)  #70% 또 조금 올라감!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7010090281465746

In [28]:
print(y_test[:5])
print(pred[:5]) #1개틀림

[ 4 11  1  7  8]
[ 3 11  1  7  8]


### Pipeline(모델결합)과 GridSearchCV를 통한 하이퍼 파라미터 튜닝
TfidfVectorizer > LogisticRegression 각각 하이퍼파라미터 설정한것을 파이프라인으로 묶묶

In [29]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([ #리스트로주고, 안에 튜플로 씁니당
    ('tfidf_vect', TfidfVectorizer(stop_words='english')),
    ('lr_clf', LogisticRegression())
])

In [30]:
#파라미터정의. 딕셔너리
params = {
    'tfidf_vect__ngram_range': [(1,1), (1,2)],  #시간이많이걸리니 2개만;
    'tfidf_vect__max_df': [300, 700],
    'lr_clf__C': [1, 10]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid_pipe = GridSearchCV(pipeline, param_grid=params, cv=3, scoring='accuracy', verbose=1)
#나중에 시간이얼마나 걸렸는지 체크하기 위해서 verbose, 코어가있다면 n_jobs
grid_pipe.fit(X_train, y_train)
print(grid_pipe.best_params_, grid_pipe.best_score_)
#결과값
# Fitting 3 folds for each of 8 candidates, totalling 24 fits
# [Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
# [Parallel(n_jobs=-1)]: Done  24 out of  24 | elapsed: 14.8min finished
# {'lr_clf__C': 10, 'tfidf_vect__max_df': 300, 'tfidf_vect__ngram_range': (1, 1)} 0.7482768582657983
#처음엔 vscode에서 (n_jobs=-1)주고 15분소요? .. 이후 모델저장못함;
#두번째 쥬피터노트북에서 15:45~ 30분넘도록안돼서 죽임
#세번째 교수님깃참고해서 컴안쓸때 돌려보자~

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 8 candidates, totalling 24 fits


In [ ]:
pred = grid_pipe.predict(X_test)
acc = accuracy_score(y_test, pred)
print(f'Count Vectorizer + Logistic Regression 정확도: {acc:.4f}')

In [ ]:
#모델저장 이게 맞나??
import joblib
joblib.dump(grid_pipe, 'model/news_pipe__tfidf_lr.pkl')